### PR TITLE
Support PHP 8.2 version for Fedora container

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds support for PHP version 8.2.

* Source are moved from 8.1 to 8.2 by `git mv`
* Version is copied back 8.2 -> 8.1
* Correct PHP version in directory 8.2 from PHP 8.1 to PHP 8.2

### CODE REVIEW

**Comment by phracek** [comment]
@remicollet @hhorak @pkubatrh Can you please review it? Only Fedora PHP-8.2 version is tested. Everything else has `.exclude` file. Thanks

**Comment by remicollet** [comment]
LGTM
Perhaps missing php.ini changes (but only about new `max_multipart_body_parts`)

```
@@ -425,6 +425,11 @@
 ; How many GET/POST/COOKIE input variables may be accepted
 ;max_input_vars = 1000
 
+; How many multipart body parts (combined input variable and file uploads) may
+; be accepted.
+; Default Value: -1 (Sum of max_input_vars and max_file_uploads)
+;max_multipart_body_parts = 1500
+
 ; Maximum amount of memory a script may consume
 ; https://php.net/memory-limit
 memory_limit = 128M

```

**Comment by phracek** [comment]
[test-all]

**Comment by joejoseph00** [comment]
https://github.com/cweagans/composer-patches/issues/559

**Comment by joejoseph00** [comment]
https://github.com/sclorg/s2i-php-container/issues/435

**Comment by joejoseph00** [comment]
For that reason, we're looking to skip 8.2 ASAP and move directly to 8.3

**Pull request merged**
