### PR TITLE
Curl instead of php readfile

### PR DESCRIPTION
**Pull request by Rydekull**
Use curl instead of php readfile to honor proxy settings.

### CODE REVIEW

**Comment by maci0** [comment]
bot, test pull request

**Comment by bparees** [comment]
[test]

@maci0 can you update this PR to fix 5.5 also?

**Comment by bparees** [comment]
@Rydekull can you update the php 5.6 image as well?
[test]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
redoing this PR here to include v5.6: https://github.com/sclorg/s2i-php-container/pull/125

**Pull request closed without merging**
