### PR TITLE
Update imagestreams for UBI8 7.4

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by phracek** [comment]
[test-openshift][test-openshift-4]

**Comment by yselkowitz** [comment]
what were the errors?

**Comment by yselkowitz** [comment]
ping?

**Comment by hhorak** [comment]
[test][test-openshift][test-openshift-4]

**Comment by hhorak** [comment]
Changes LGTM, let's wait for the tests feedback

**Comment by hhorak** [comment]
The tests are somehow broken, so I've verified this manually with OCP 4.6, looks good, merging.

**Pull request merged**
