### PR TITLE
Add imagestreams for RHEL9 and PHP-81

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds imiagestreams for PHP-81 and RHEL9/UBI9

### CODE REVIEW

**Comment by phracek** [comment]
@yselkowitz PTAL. Thanks

**Comment by phracek** [comment]
[test-openshift]

**Comment by cuppett** [comment]
@phracek Should we also add php 8.2? That appears available now as well.

https://access.redhat.com/solutions/7024181

**Comment by phracek** [comment]
> @phracek Should we also add php 8.2? That appears available now as well.
> 
> https://access.redhat.com/solutions/7024181

Hi Stephen,

PHP-8.2 for Fedora is already available in quay.io https://quay.io/repository/fedora/php-82, but for RHEL8 and RHEL9 no, and I don't know if it is planned.

**Review by zmiklank — APPROVED** [review]
did not hit any issues.

**Pull request merged**
