### PR TITLE
 The track_errors ini directive has been removed in PHP 8.0.

### PR DESCRIPTION
**Pull request by xrow**
The track_errors ini directive has been removed in PHP 8.0. This means that php_errormsg is no longer available. 

https://www.php.net/manual/en/migration80.php

I see unneded log output and error, when you still have to set to ON:

```
2024-07-23T12:04:44.275489753Z [23-Jul-2024 14:04:44] NOTICE: PHP message: PHP Fatal error:  Directive 'track_errors' is no longer available in PHP in Unknown on line 0
2024-07-23T12:04:44.275542281Z <br />
2024-07-23T12:04:44.275547959Z <b>Fatal error</b>:  Directive 'track_errors' is no longer available in PHP in <b>Unknown</b> on line <b>0</b><br />
```

If this pull gets accepted will this fix https://catalog.redhat.com/software/containers/ubi9/php-82/657b0176999f2e3662c8159b in the future?

### CODE REVIEW

**Comment by hhorak** [comment]
@remicollet can you, please, look at this?

**Comment by remicollet** [comment]
LGTM

**Review by remicollet — APPROVED** [review]
LGTM

**Comment by xrow** [comment]
@hhorak Anythign i need todo?

**Comment by phracek** [comment]
As soon as tests passed, I will merge them. We already have approve

[test-all]

**Review by phracek — APPROVED** [review]

**Pull request merged**
