### PR TITLE
Fix for PHP S2I Opcache configuration

### LINKED ISSUE #150: s2i run script writes 10-opcache.ini to wrong path
While investigating #149 I found that the S2I run script writes our the 10-opcache.ini file to /etc/opt/rh/rh-php70/ directory instead of the scanned /etc/opt/rh/rh-php70/php.d directory

`envsubst < /opt/app-root/etc/php.d/10-opcache.ini.template > /etc/opt/rh/rh-php70/10-opcache.ini`

php -i shows that we don't load the file from the rh-php70 directory

> Loaded Configuration File => /etc/opt/rh/rh-php70/php.ini                                                                                                                                                                                     
> Scan this dir for additional .ini files => /etc/opt/rh/rh-php70/php.d                                                                                                                                                                         
> Additional .ini files parsed => /etc/opt/rh/rh-php70/php.d/10-opcache.ini,

### PR DESCRIPTION
**Pull request by lucasnetau**
Fixes #150 and #149

### CODE REVIEW

**Comment by andrewklau** [comment]
@hhorak @bparees fyi

**Comment by caruccio** [comment]
+1

**Comment by bparees** [comment]
lgtm, thanks @lucasnetau

**Comment by remicollet** [comment]
opcache.memory_consumption is obviously to small

```
$ php -d opcache.enable_cli=1 -d opcache.memory_consumption=16 -d opcache.interned_strings_buffer=8 -v
Thu Mar 16 11:08:39 2017 (20578): Fatal Error Zend OPcache cannot allocate buffer for interned strings

$ php -d opcache.enable_cli=1 -d opcache.memory_consumption=24 -d opcache.interned_strings_buffer=8 -v
PHP 7.0.17 (cli) (built: Mar 14 2017 14:39:53) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.17, Copyright (c) 1999-2017, by Zend Technologies

```

**Comment by lucasnetau** [comment]
@omron93 Please see #152 which explains the issue. This patch corrected the installation of the opcache profile, I left the defaults as set in the original file.

Unfortunately in all my environments I have OPCACHE_MEMORY_CONSUMPTION to values greater than 16 so did not pick up on the issue until after the pull request was merged.

Setting OPCACHE_MEMORY_CONSUMPTION=18 or higher will allow the container to run. I've posed a question to the maintainers as to what a sensible default should be.

**Comment by omron93** [comment]
@lucasnetau @remicollet Thanks for help and quick fix.

**Comment by bparees** [comment]
@remicollet sorry, I saw green and thought it meant the tests had run, didn't notice that the bot was asking for admin approval before running tests.

**Pull request merged**
