### PR TITLE
remove EOL versions

### PR DESCRIPTION
**Pull request by zmiklank**
This code is no longer maintained.

I've noticed, that for example `test/run` files are copied and not symlinked to the main `test/run` and that makes them un-maintanable.

Do you think we can remove the EOL versions?

### CODE REVIEW

**Comment by zmiklank** [comment]
[test-all]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-openshift]

**Review by phracek — CHANGES_REQUESTED** [review]
It would be nice to have in comment, what versions have been removed.

**Comment by zmiklank** [comment]
> It would be nice to have in comment, what versions have been removed.

Done.

**Review by phracek — APPROVED** [review]
LGTM. Thanks for removing deprecated versions.

**Pull request merged**
