### PR TITLE
Proper cleanup

### PR DESCRIPTION
**Pull request by zmiklank**
Some comments are in the commit messages.

Also I am not really sure about the [ssl test](https://github.com/sclorg/s2i-php-container/blob/5e506d17362bfb3ae3398fb277dce0da682decbf/test/run#L202). Seem to be incomplete. Can you please take a look at it while reviewing this?

### CODE REVIEW

**Comment by zmiklank** [comment]
[test-all]

**Review by phracek — APPROVED** [review]
LGTM. Let's wait for OpenShift 4 tests.

**Comment by zmiklank** [comment]
@phracek and what about the ssl test I've mentioned?

**Comment by zmiklank** [comment]
> @phracek and what about the ssl test I've mentioned?

I've created [an issue](https://github.com/sclorg/s2i-php-container/issues/399) for that.

**Comment by zmiklank** [comment]
Merging, as this already has LGTM and the OCP tests are not related.

**Pull request merged**
