### PR TITLE
This pull request enables testing PHP-82 in RHEL8 and RHEL9

### PR DESCRIPTION
**Pull request by phracek**
This pull request enables testing PHP-8.2 in RHEL8 and RHEL9

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Review by zmiklank — APPROVED** [review]
Modules does not seem to be available yet for php 8.2. LGTM.

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Let's try one more time

[test]

**Comment by phracek** [comment]
[test-openshift]

**Pull request merged**
