### PR TITLE
Fix issue 316

### LINKED ISSUE #316: Building Nodejs failed on `chmod Operation not permitted` on Fedora, CentOS7 and RHEL7
By this PR https://github.com/sclorg/s2i-php-container/pull/309 

Log from Fedora:

```bash
Step 3/4 : RUN TEMPFILE=$(mktemp) &&     curl -o "$TEMPFILE" "https://getcomposer.org/installer" &&     php <"$TEMPFILE" &&     ./composer.phar install --no-interaction --no-ansi --optimize-autoloader
 ---> Running in 870d4ae6a70d

 [91m [0m [91m  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent [0m [91m    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 [0m [91m
100  269k  100  269k    0     0   682k      0 --:--:-- --:--:-- --:--:--  684k
 [0mAll settings correct for using Composer
Downloading...

Composer (version 2.0.6) successfully installed to: /opt/app-root/src/composer.phar
Use it: php composer.phar

 [91mInstalling dependencies from lock file (including require-dev)
 [0m [91mVerifying lock file contents can be installed on current platform.
[snipped]
 [0m [91m  - Installing psy/psysh (v0.10.4): Extracting archive
 [0m [91mPackage asm89/twig-cache-extension is abandoned, you should avoid using it. Use twig/cache-extension instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
 [0m [91m24 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
 [0m [91m> App\Console\Installer::postInstall
Script App\Console\Installer::postInstall handling the post-install-cmd event terminated with an exception

 [0mCreated `/opt/app-root/src/tmp` directory
Created `/opt/app-root/src/tmp/cache` directory
Created `/opt/app-root/src/tmp/cache/models` directory
Created `/opt/app-root/src/tmp/cache/persistent` directory
Created `/opt/app-root/src/tmp/cache/views` directory
Created `/opt/app-root/src/tmp/sessions` directory
Created `/opt/app-root/src/tmp/tests` directory
Permissions set on /opt/app-root/src/tmp/cache
Permissions set on /opt/app-root/src/tmp/cache/models
Permissions set on /opt/app-root/src/tmp/cache/persistent
Permissions set on /opt/app-root/src/tmp/cache/views
Permissions set on /opt/app-root/src/tmp/sessions
Permissions set on /opt/app-root/src/tmp/tests
Permissions set on /opt/app-root/src/tmp
 [91m                                    
  [ErrorException]                  
  chmod(): Operation not permitted  
                                    
```

### PR DESCRIPTION
**Pull request by phracek**
This commit fixes #316 .

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
@fila43 Please take a look on it

**Comment by fila43** [comment]
it looks like php needs to modify ownership or permissions of the app directory, so your change makes sense

**Comment by phracek** [comment]
@hhorak @pkubatrh PTAL. This is similar like here: https://github.com/sclorg/nginx-container/pull/131/files#diff-2d4e25b65b2f08aae04434a066fb93e93cb25900ce42821469de314459db0e2fR129

**Comment by phracek** [comment]
[test]

**Comment by hhorak** [comment]
LGTM.

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Pull request merged**
