### PR TITLE
Remove xdebug from PHP 5.6

### LINKED ISSUE #122: disable xdebug option
It seems strange to be including xdebug for prod containers, it'd be ideal if we could add an option to disable this by ENV variable (or not include it at all?)

### PR DESCRIPTION
**Pull request by andrewklau**
Fixes #122 and #139 

@joellarson is right about memcache however this might potentially effect some users(?)

### CODE REVIEW

**Comment by andrewklau** [comment]
@bparees ping

**Comment by JoelLarson** [comment]
It would be totally fine to have both memcache and memcached installed, though the memcached extension does everything the memcache extension does.

**Comment by bparees** [comment]
this is up to @hhorak and team at this point, but i'm definitely wary of the possibility that we break users who's apps expect this module is installed.  It might be better to just tell people to turn it off if they care.

**Comment by sebas5384** [comment]
XDebug could be enabled optionally, not by default. Installed by default isn't the problem in my opinion.

**Pull request closed without merging**
