### PR TITLE
Add testing cake-php ex repositories properly

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds testing cake-php-ex repository properly
in s2i-php-container

### CODE REVIEW

**Comment by phracek** [comment]
[test-openshift]

**Review by zmiklank — COMMENTED** [review]
Thanks for the PR.

Wouldn't the cakephp app be easier to maintain if we branch it out for php 7.3 -  staying on older cakephp version, and use master branch for newer cakephp versions?

Or do you want to just merge the 4.X branch to master, when php 7.3 is EOL for us?

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
> Thanks for the PR.
> 
> Wouldn't the cakephp app be easier to maintain if we branch it out for php 7.3 - staying on older cakephp version, and use master branch for newer cakephp versions?
> 
> Or do you want to just merge the 4.X branch to master, when php 7.3 is EOL for us?

For now we should support all of them.  `master` branch that supports `php-73`, `4.X` branch that supports `PHP 7.4 and PHP 8.0` and `5.X` branch that supports `PHP-8.1 and PHP-82`

**Review by zmiklank — APPROVED** [review]

**Pull request merged**
