### PR TITLE
Add php-gmp module

### PR DESCRIPTION
**Pull request by hug-abacus**
Please add the php gmp module to the s2i image.

### CODE REVIEW

**Comment by hhorak** [comment]
Sounds fine to you, @remicollet ?

**Comment by remicollet** [comment]
Yes, lgtm (+ same in php 7.0)

**Comment by remicollet** [comment]
BTW, perhaps we should not accept any change for PHP 5.5 which is EOL
Only 5.6 and 7.0 are now maintained

**Comment by hug-abacus** [comment]
@remicollet is php7.0 in a different repo?

**Comment by remicollet** [comment]
No, see PR #134

**Pull request merged**
