### PR TITLE
Remove deprecated GMT timezone with UTC

### PR DESCRIPTION
**Pull request by wgordon17**

### CODE REVIEW

**Comment by wgordon17** [comment]
Based on the warning in http://php.net/manual/en/timezones.others.php

> **Warning** Please do not use any of the timezones listed here (besides UTC), they only exist for backward compatible reasons, and may expose erroneous behavior.

It is necessary to replace `GMT` with `UTC` in the `php.ini.template` files for all PHP versions

**Comment by wgordon17** [comment]
This is to address: https://bugzilla.redhat.com/show_bug.cgi?id=1662714

**Comment by notroj** [comment]
LGTM, @remicollet this is OK to merge?

**Comment by remicollet** [comment]
ok for me excepted in the EOL 5.x versions and missing 7.2

**Comment by wgordon17** [comment]
@remicollet Updated to remove changes from 5.X versions and include 7.2

**Comment by wgordon17** [comment]
@remicollet @notroj Is this ready to be merged?

**Comment by pkubatrh** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
@wgordon17 Can you please rebase it on the top of master, so we can merge it?

**Comment by wgordon17** [comment]
[test-all]

**Comment by wgordon17** [comment]
@phracek rebased and all wrapped up into a single commit

**Comment by phracek** [comment]
@wgordon17 We have to rebase this pull request and as soon as the tests are passing, we can merge it. Can you please rebase it? I will focus on this issue.

**Comment by wgordon17** [comment]
@phracek rebased

**Comment by zmiklank** [comment]
[test-all]

**Review by zmiklank — APPROVED** [review]

**Review by phracek — APPROVED** [review]
LGTM.

**Pull request merged**
