### PR TITLE
enable centos7/rhel7/fedora builds for 7.3

### PR DESCRIPTION
**Pull request by pkubatrh**
Resolves: #277

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by xrow** [comment]
@phracek Will this new build available here ( https://hub.docker.com/r/centos/php-73-centos7 ) ?

**Comment by pkubatrh** [comment]
Added new public image functions from commons.

>Will this new build available here ( https://hub.docker.com/r/centos/php-73-centos7 ) ?

Yes, once this PR is merged the centos7 image will be built and pushed to dockerhub.

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
Thanks for review. Tests are green so merging.

**Pull request merged**
