### PR TITLE
PHP72

### PR DESCRIPTION
**Pull request by madrisan**
This patch adds the PHP 7.2 version, now available in Red Hat Software Collection.

### CODE REVIEW

**Comment by hhorak** [comment]
Thanks for the contribution.

One thing I spotted: The `.*image-id*` files are actually not supposed to be part of the repo, so those can be either removed from the PR, or it would be probably better to add them to the `.gitignore`, similar as it is done for postgresql image: https://github.com/sclorg/postgresql-container/blob/master/.gitignore

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
Thanks for the PR!

php 7.2 is in the process of being added via https://github.com/sclorg/s2i-php-container/pull/239 so I will be closing your PR in favour of https://github.com/sclorg/s2i-php-container/pull/239.

**Pull request closed without merging**
