### PR TITLE
Imagestream generator

### PR DESCRIPTION
**Pull request by zmiklank**
This PR removes tag "7.3" as it not standard for other sclorg images. I also removes tring `"supports":"php:8.0,php"` from the tag. Could that cause a problem?

### CODE REVIEW

**Comment by zmiklank** [comment]
[test-openshift]

**Comment by zmiklank** [comment]
[test-openshift]

**Comment by zmiklank** [comment]
@phracek seems like problem with ansible scripts?

**Comment by phracek** [comment]
> @phracek seems like problem with ansible scripts?

No problem with subscription: ```"The system is unable to complete the requested transaction (HTTP error code 500: Internal Server Error)"```

**Comment by phracek** [comment]
[test-openshift]

**Review by phracek — APPROVED** [review]
LGTM

**Comment by zmiklank** [comment]
We need an answer for the first question before merging this:

> This PR removes tag "7.3" as it not standard for other sclorg images. I also removes tring "supports":"php:8.0,php" from the tag. Could that cause a problem?

**Comment by zmiklank** [comment]
> We need an answer for the first question before merging this:
> 
> > This PR removes tag "7.3" as it not standard for other sclorg images. I also removes tring "supports":"php:8.0,php" from the tag. Could that cause a problem?

@pkubat WDYT?

**Comment by phracek** [comment]
PHP-7.3 is still supported for RHEL7 images. I don't follow what you mean by removing tag '7.3'?

**Comment by zmiklank** [comment]
> PHP-7.3 is still supported for RHEL7 images. I don't follow what you mean by removing tag '7.3'?

There is "7.3-ubi7" and a "7.3" tag. Those are two different tags we provide, the "7.3" being non-standard - not all container images' imagrestreams provide it. Currently the imagestream generator can not generate tags in format of app version only (7.3).

**Comment by pkubatrh** [comment]
LGTM. The change might cause some minor breakege, but since we are standardizing on a specific name format I say this is worth the risk.

**Review by phracek — APPROVED** [review]
LGTM again.

**Pull request merged**
