### PR TITLE
Define module dir so the config file is put to the correct directory

### PR DESCRIPTION
**Pull request by hhorak**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1860561
This also moves the tests/run script to a common directory, so the code is not duplicated.

### CODE REVIEW

**Comment by hhorak** [comment]
[test]

**Comment by pkubatrh** [comment]
[test]

**Comment by pkubatrh** [comment]
Ah I see the PR needs to be rebased first due to conflicts in `test/run`

**Comment by remicollet** [comment]
LGTM

**Pull request merged**
