### PR TITLE
Add session save handler to allow redis to be provided

### PR DESCRIPTION
**Pull request by bobbydeveaux**
We'd like to support passing in 'redis' as the save handler to the s2i image. Rather than create a whole new Docker file and custom config, I'd rather add it here for all to use. :)

### CODE REVIEW

**Comment by omron93** [comment]
@bobbydeveaux Thanks for this contribution. Please change also `5.6` and `7.0` README.
Otherwise LGTM.

@remicollet Please review too.

**Comment by omron93** [comment]
[test]

**Comment by remicollet** [comment]
I don't thinkg this can work

1/ you need to define both **session.save_handler** and **session.save_path** 

2/ this value are inherits from apache configuration (user specific) nbot from php configuration (common to all users), see httpd/conf.d/php.conf

**Comment by remicollet** [comment]
forget 1/ (SESSION_PATH variable exists)

**Comment by remicollet** [comment]
See https://github.com/sclorg/s2i-php-container/blob/master/7.1/root/usr/share/container-scripts/php/common.sh#L24

Should be enought o
```
- sed -i '/php_value session.save_path/d'  ...
+ sed -i '/php_value session.save_/d'  ...
```

**Comment by bobbydeveaux** [comment]
What do you make of the change now @remicollet ? :)

**Comment by bobbydeveaux** [comment]
@omron93 - thoughts? :)

**Comment by bobbydeveaux** [comment]
Hey guys, it'd be good to see this through @omron93 @remicollet

**Comment by bobbydeveaux** [comment]
@centos-ci @rhscl-bot

**Comment by remicollet** [comment]
lgtm

**Comment by omron93** [comment]
I don't see problem with this too. @bobbydeveaux Thanks for contribution.

**Comment by omron93** [comment]
[test]

I'll merge it if tests pass.

**Comment by omron93** [comment]
[test-openshift]

**Pull request merged**
