### PR TITLE
Update fedora versions for s2i-php-container

### PR DESCRIPTION
**Pull request by phracek**
This pull request deprecates testing s2i-php-container version 7.3, 7.4 and 8.0 till
Fedora 35.

From Fedora 36 it is used 8.1.

### CODE REVIEW

**Comment by phracek** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
LGTM

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
OpenShift 4 failures are not connected to this pull request.

**Pull request merged**
