### PR TITLE
retry https://getcomposer.org/installer download if it fails

### PR DESCRIPTION
**Pull request by jim-minter**
We're getting periodic test flakes on Origin due to failure to download https://getcomposer.org/installer, it would be useful to see if a retry helps
https://github.com/openshift/origin/issues/16772
@bparees

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by omron93** [comment]
[test]

LGTM, thanks for the fix.

@bparees We was forced to do a change in CentOS CI - to be able to trigger it you have to be **public** member of sclorg/ github org.

**Comment by omron93** [comment]
@jim-minter Why not to use `curl --retry 5 --retry-delay 10`?

**Comment by jim-minter** [comment]
@omron93 according to the curl docs, `--retry` retries on a "transient error" ("a timeout, an FTP 4xx response code or an HTTP 5xx response code").  It's not clear to me that the error we're seeing fits into any of those categories.

**Comment by omron93** [comment]
> according to the curl docs, --retry retries on a "transient error" ("a timeout, an FTP 4xx response code or an HTTP 5xx response code"). It's not clear to me that the error we're seeing fits into any of those categories.

Thanks for explanation.

**Comment by omron93** [comment]
@jim-minter Thanks for this fix.

**Pull request merged**
