### PR TITLE
remove centos7 testing repositories

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by phracek** [comment]
It would be nice to have a result why POD did not come ready https://gist.github.com/rhscl-bot/399ec0aac1d605f5183bcb004f1629b5#file-s2i-php-container-48-sh-L4513 .

```bash
87ce3c710641: Pushed
7.3: digest: sha256:7465763253ca80c66c2066f926a2434d176f6d5510e9f78e74deec1ee86d8fd2 size: 1372
Waiting for php-73-rhel7-2 pod becoming ready ....................... FAIL
make: *** [test-openshift] Error 1
Build step 'Execute shell' marked build as failure
```
I will try to do it in container-common-script as a PR.

**Comment by pkubatrh** [comment]
>I will try to do it in container-common-script as a PR.

Note there already is: https://github.com/sclorg/container-common-scripts/blob/master/test-lib-openshift.sh#L63

**Pull request merged**
