### PR TITLE
fix dangling run-openshift symlink

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by hhorak** [comment]
LGTM, we can merge once openshift tests pass.

**Comment by hhorak** [comment]
[test-openshift]

**Comment by hhorak** [comment]
[test]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
Tests green, merging.

**Pull request merged**
