### PR TITLE
Add php 7.0

### PR DESCRIPTION
**Pull request by hhorak**

### CODE REVIEW

**Comment by bparees** [comment]
pending the outcome of https://github.com/sclorg/s2i-php-container/pull/133, this may need a tweak to stay aligned with the other versions.

**Comment by hhorak** [comment]
> pending the outcome of #133, this may need a tweak to stay aligned with the other versions.

Thanks for the notice, I'll wait for what @remicollet says about it and will add if it is gonna be used in 5.6.

**Comment by bparees** [comment]
@hhorak ok we merged #133

**Comment by hhorak** [comment]
> @hhorak ok we merged #133

Also did for this PR.

**Comment by hhorak** [comment]
@remicollet @bparees I'd like to merge this, so we take the latest changes to next rebuild. Is it ok?

**Comment by bparees** [comment]
@hhorak i don't think i'm in a position to sign off on(or reject) it at this point, it's entirely up to you guys as the SCL team.  if you have specific concerns from an openshift perspective, let me know and i can provide feedback.

**Comment by hhorak** [comment]
@remicollet Let me know if you spot an issue, otherwise will merge tomorrow, because of next rebuild, as mentioned above.

**Comment by remicollet** [comment]
LGTM +1

**Pull request merged**
