### PR TITLE
Support testing template

### PR DESCRIPTION
**Pull request by phracek**
Add test case for cakephp-ex template

    Supported test scenarios are only
    RHEL8 and VERSION=7.4
    RHEL7 and VERSION=7.3

    The rest will be solved by issue
    https://github.com/sclorg/cakephp-ex/issues/136

### CODE REVIEW

**Comment by phracek** [comment]
I have detected that directory 8.1/test has not links to test directory like the others. Therefore first commit fixing it.
The next commit brings testing template for specific version the rest are not solved yet in examples repository. See https://github.com/sclorg/cakephp-ex/issues/136

**Comment by phracek** [comment]
[test-all]

**Comment by zmiklank** [comment]
The code lgtm, but let's wait for the tests to finish.

**Comment by phracek** [comment]
RHEL7 - OpenShift 3 - 7.3 failed because OpenShift 3 did not start properly:

```
I1107 07:27:36.541734   18714 apply_template.go:81] Installing "kube-dns"
I1107 07:27:36.541991   18714 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I1107 07:27:42.585508   18714 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.

OpenShift tests for rhscl/php-73-rhel7:1 failed.
errexit on line 63, common/test.sh
make: *** [test-openshift] Error 1
```

**Pull request merged**
